// <auto-generated />
using DinoWebAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DinoWebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230706095502_Foreignkeys")]
    partial class Foreignkeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("DinoWebAPI.Dinosaur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentContinent")
                        .IsRequired()
                        .HasColumnType("nvarchar (40)");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Era")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WheightInTons")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Dinosaurs");
                });

            modelBuilder.Entity("DinoWebAPI.ReptileMar", b =>
                {
                    b.Property<int>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("WheightInTons")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Size", "WheightInTons");

                    b.HasIndex("Id1", "Id2");

                    b.ToTable("ReptileMars");
                });

            modelBuilder.Entity("DinoWebAPI.ReptileVol", b =>
                {
                    b.Property<int>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("WheightInTons")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Size", "WheightInTons");

                    b.ToTable("ReptileVols");
                });

            modelBuilder.Entity("DinoWebAPI.ReptileMar", b =>
                {
                    b.HasOne("DinoWebAPI.ReptileVol", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("Id1", "Id2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DinoWebAPI.ReptileVol", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
